NAMES = {
    "Barcelona Dragons": {"short": "BD"},
    "Berlin Thunder": {"short": "BT"},
    "Cologne Centurions": {"short": "CC"},
    "Fehérvár Enthroners": {"short": "EF"},
    "Fehervar Enthroners": {"short": "ENT"},
    "Frankfurt Galaxy": {"short": "FG"},
    "Hamburg Sea Devils": {"short": "HD"},
    "Helvetic Guards": {"short": "HG"},
    "Helvetic Mercenaries": {"short": "HM"},
    "Madrid Bravos": {"short": "MB"},
    "Milano Seamen": {"short": "MS"},
    "Munich Ravens": {"short": "MR"},
    "Paris Musketeers": {"short": "PM"},
    "Prague Lions": {"short": "PL"},
    "Raiders Tirol": {"short": "RT"},
    "Rhein Fire": {"short": "RF"},
    "Stuttgart Surge": {"short": "SRG"},
    "Vienna Vikings": {"short": "VV"},
    "Wroclaw Panthers": {"short": "PW"},
    "Copenhagen Towers": {"short": "CTW"},
}
